<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_classFrame</name>
   <tag></tag>
   <elementGuidId>ca614c32-fb1b-4e70-94e7-e46aa8052db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;classFrame&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='classFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a8d91aa0-2d28-4fb0-bd8f-b4c641697736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>overview-summary.html</value>
      <webElementGuid>773f45b4-f95e-47c9-80af-258b6ad490b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>f9201b97-93fe-4a33-a4e8-42e2ac0aa9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Package, class and interface descriptions</value>
      <webElementGuid>2033176d-8500-40a5-aad6-5231aae223b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rightIframe</value>
      <webElementGuid>362b514b-e993-44e0-8b35-90df1d7ebc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;rightContainer&quot;]/iframe[@class=&quot;rightIframe&quot;]</value>
      <webElementGuid>7676618c-8498-4a6c-aa4b-e792362a86e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='classFrame']</value>
      <webElementGuid>583b18a4-11b1-43a0-83bb-b6adf699a041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>96bc4481-64fe-46e9-87ca-30299fc0d193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'overview-summary.html' and @name = 'classFrame' and @title = 'Package, class and interface descriptions']</value>
      <webElementGuid>86bd07b7-d61b-4e80-94e0-56b7cc5b14ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
