<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Recruitment</name>
   <tag></tag>
   <elementGuidId>e01c7988-f8da-4828-9130-79f3140db465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_recruitment_viewRecruitmentModule > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_recruitment_viewRecruitmentModule']/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>99af726d-fbd5-49b8-a540-dc9c42db4795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recruitment</value>
      <webElementGuid>b2b4c264-4871-4a88-b8b7-b45db9b32c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_recruitment_viewRecruitmentModule&quot;)/b[1]</value>
      <webElementGuid>30d9b147-4248-4698-9b17-2e41e5f89fcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu_recruitment_viewRecruitmentModule']/b</value>
      <webElementGuid>a431a52b-94bd-4463-be61-b5c5cc01f828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[1]/following::b[1]</value>
      <webElementGuid>bc5bb471-70d9-4e67-a82c-c3ce69b9ee87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customers'])[1]/following::b[1]</value>
      <webElementGuid>c705f49d-375f-4a92-95b4-2a09e5bf2df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidates'])[1]/preceding::b[1]</value>
      <webElementGuid>b54d164e-c22c-4d89-8447-f4a1541b519a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacancies'])[1]/preceding::b[1]</value>
      <webElementGuid>2672e5bc-66d8-4b3c-a67b-e9bdef184b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recruitment']/parent::*</value>
      <webElementGuid>5c90cef7-71b0-486f-9ebf-64c00bf14b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/b</value>
      <webElementGuid>48cb73c1-1bf6-4de2-888c-555a19d599f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Recruitment' or . = 'Recruitment')]</value>
      <webElementGuid>633b727a-c339-4d3f-89b7-05501fce4fcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
